version: "3.7"

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - "mongodb-vol:/data/db"
    ports:
      - "27017:27017"
volumes:
  mongodb-vol:

# mongodb://mongo:mongo@127.0.0.1:27017/admin